### ISSUE TITLE
Error installing lean using elan on darwin

### ISSUE THREAD

**Issue by evhub** [Kha/elan#20]
After using `elan-init.sh` to install elan + lean as in the README, I get the following error when running the `lean` command:
```bash
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/evan/.elan/toolchains/stable/bin/lean
  Reason: image not found
Abort trap: 6
```

Furthermore, when I run `elan show`, I get
```bash
stable (default)
(error reading lean version)
```

Any idea what might be the problem? I'm on OS X Mojave 10.14.5.

**Comment by evhub** [comment]
I ran `brew install gmp` and it fixed the problem, though presumably elan should be running that for me?

**Comment by Kha** [comment]
This is a known issue with the official Lean releases for macOS. It will definitely be fixed in Lean 4, though probably not in Lean 3 anymore. I don't really want elan to fix Lean issues, but you may want to open an issue at https://github.com/leanprover-community/lean to fix it in a community release of Lean 3.

**Comment by dwrensha** [comment]
I hit this issue too, and I did not want to install Homebrew because I usually use MacPorts.

I worked around the problem by copying the MacPorts version of the dynamic library to the Homebrew path:

```
$ sudo mkdir -p /usr/local/opt/gmp/lib
$ sudo cp /opt/local/lib/libgmp.10.dylib /usr/local/opt/gmp/lib/
```

**Comment by Kha** [comment]
Closing in favor of https://github.com/leanprover-community/lean/issues/118
